/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Knight(props) {
    const {animation} = props;
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/knightTPose.glb");

  const { animations: runningAnimation } = useFBX("animations/Run.fbx")

  runningAnimation[0].name ="Run";

  const { actions } = useAnimations([runningAnimation[0]], group);

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => {
      actions[animation].reset().fadeOut(0.5)
    }
  }, [animation])

  return (
    <group ref={group} {...props} rotation-x={-Math.PI / 2} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="Paladin_J_Nordstrom"
            geometry={nodes.Paladin_J_Nordstrom.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Helmet"
            geometry={nodes.Paladin_J_Nordstrom_Helmet.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Helmet.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Shield"
            geometry={nodes.Paladin_J_Nordstrom_Shield.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Shield.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Sword"
            geometry={nodes.Paladin_J_Nordstrom_Sword.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Sword.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/knightTPose.glb");